title: Kubed Documentation
description: Documentation and cheat sheets for Docker, Kubernetes, Terraform, and Helm
baseurl: "/kubed"
url: "https://dalefrieswthat.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/

# Navigation
nav_order: 1
nav_exclude: false

# Footer
footer:
  content: "© 2024 Dale Yarborough. All rights reserved."
  links:
    - label: GitHub
      url: https://github.com/dalefrieswthat/kubed

# Social links
social:
  - label: GitHub
    url: https://github.com/dalefrieswthat/kubed
  - label: Email
    url: mailto:daleyarborough@gmail.com 